### ISSUE TITLE
[Privacy] En-tête X-Content-Type-Options absente

### ISSUE THREAD

**Issue by KuSh** [digital4better/monaplie#63]
Recommendation fruggr.

L'en-tête anti-MIME-Sniffing X-Content-Type-Options n'a pas été défini sur "nosniff". Cela permet aux anciennes versions d'Internet Explorer et de Chrome d'effectuer un reniflage MIME sur le corps de la réponse, ce qui peut entraîner l'interprétation et l'affichage du corps de la réponse comme un type de contenu autre que le type de contenu déclaré. Les versions actuelles (début 2014) et anciennes de Firefox utiliseront le type de contenu déclaré (s'il y en a un), plutôt que d'effectuer un reniflage MIME. [Plus d'information en anglais](https://www.zaproxy.org/docs/alerts/10021/)

Passer par une balise meta puisqu'on n'a pas la main sur les headers avec github pages

**Comment by FlorineGermond** [comment]
@KuSh Début l'implémentation sur la branche fruggr-x-content-type

**Comment by KuSh** [comment]
Balise à mettre dans app.html
