### ISSUE TITLE
[Perf] Utiliser des écouteurs passifs pour améliorer les performances de défilement

### ISSUE THREAD

**Issue by KuSh** [digital4better/monaplie#66]
Voir avec lighthouse en mobile pour avoir plus de précision sur les éléments à corriger. Certainement lié aux boutons de scroll.

Plus d'information en anglais : https://web.dev/uses-passive-event-listeners/

**Comment by FlorineGermond** [comment]
Vérifier si, depuis la suppression des boutons de scroll, fruggr renvoi tjr cette suggestion

**Comment by KuSh** [comment]
C'est bien le cas 👍
